// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"
#include <stdio.h>

int count = 0;

void countClicks(lv_event_t * e)
{
	// Your code here
	char str[10];
	count++;
	sprintf(str, "%d", count);
	lv_label_set_text(ui_Label4, str);
}
